package de.dhbw.projektarbeit.gui;

import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import de.dhbw.projektarbeit.customer.*;

import de.dhbw.projektarbeit.customer.NewCustomer;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * 
 * @author Albert
 */
public class GUI extends javax.swing.JFrame {

	/**
	 * Creates new form GUI
	 */
	public GUI() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jDialog1 = new javax.swing.JDialog();
		jPanel7 = new javax.swing.JPanel();
		jTextField1 = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jTextField10 = new javax.swing.JTextField();
		jLabel16 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jTextField9 = new javax.swing.JTextField();
		jLabel18 = new javax.swing.JLabel();
		jTextField11 = new javax.swing.JTextField();
		jLabel19 = new javax.swing.JLabel();
		jTextField12 = new javax.swing.JTextField();
		jLabel20 = new javax.swing.JLabel();
		jTextField13 = new javax.swing.JTextField();
		jTextField14 = new javax.swing.JTextField();
		jLabel21 = new javax.swing.JLabel();
		jLabel22 = new javax.swing.JLabel();
		jComboBox4 = new javax.swing.JComboBox();
		jComboBox5 = new javax.swing.JComboBox();
		jComboBox6 = new javax.swing.JComboBox();
		jTextField3 = new javax.swing.JTextField();
		jPanel8 = new javax.swing.JPanel();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jDialog2 = new javax.swing.JDialog();
		jPanel9 = new javax.swing.JPanel();
		jLabel9 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jTextField5 = new javax.swing.JTextField();
		jLabel11 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jTextField8 = new javax.swing.JTextField();
		jLabel15 = new javax.swing.JLabel();
		jComboBox3 = new javax.swing.JComboBox();
		jPanel1 = new javax.swing.JPanel();
		jSplitPane1 = new javax.swing.JSplitPane();
		jPanel5 = new javax.swing.JPanel();
		jSplitPane2 = new javax.swing.JSplitPane();
		jPanel4 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jPanel6 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jButton2 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jLabel7 = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		NewCustomer cnw = new NewCustomer();

		jDialog1.setResizable(false);

		jPanel7.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Neuen Kunden anlegen"));

		jLabel8.setText("Vorname");

		jLabel16.setText("Nachname");

		jLabel17.setText("Stra§e und Hausnummer");

		jLabel18.setText("PLZ");

		jLabel19.setText("Ort");

		jLabel20.setText("E-Mail Adresse");

		jLabel21.setText("Geburtsdatum");

		jLabel22.setText("Telefonnummer");

		jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12",
				"13", "14", "15", "16", "17", "18", "19", "20", "21", "22",
				"23", "24", "25", "26", "27", "28", "29", "30", "31" }));
		jComboBox4.addActionListener(new java.awt.event.ActionListener() {

			public void actionPerformed(ActionEvent evt) {
				String date = (String) jComboBox4.getSelectedItem();

			}

		});

		jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Januar", "Februar", "MŠrz", "April", "Mai", "Juni", "Juli",
				"August", "September", "Oktober", "November", "Dezember" }));

		jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"1900", "1901", "1902", "2000", "2001", "2002", " " }));

		org.jdesktop.layout.GroupLayout jPanel7Layout = new org.jdesktop.layout.GroupLayout(
				jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout
				.setHorizontalGroup(jPanel7Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel7Layout
								.createSequentialGroup()
								.addContainerGap()
								.add(jPanel7Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jPanel7Layout
												.createSequentialGroup()
												.add(jLabel21)
												.add(0, 0, Short.MAX_VALUE))
										.add(org.jdesktop.layout.GroupLayout.TRAILING,
												jPanel7Layout
														.createSequentialGroup()
														.add(jPanel7Layout
																.createParallelGroup(
																		org.jdesktop.layout.GroupLayout.TRAILING)
																.add(jPanel7Layout
																		.createSequentialGroup()
																		.add(0,
																				0,
																				Short.MAX_VALUE)
																		.add(jTextField14,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				327,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																.add(jPanel7Layout
																		.createSequentialGroup()
																		.add(0,
																				0,
																				Short.MAX_VALUE)
																		.add(jPanel7Layout
																				.createParallelGroup(
																						org.jdesktop.layout.GroupLayout.LEADING)
																				.add(jLabel20)
																				.add(jPanel7Layout
																						.createSequentialGroup()
																						.add(jPanel7Layout
																								.createParallelGroup(
																										org.jdesktop.layout.GroupLayout.LEADING)
																								.add(jLabel8)
																								.add(jTextField1,
																										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																										156,
																										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																								.add(jLabel18)
																								.add(jTextField11,
																										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																										156,
																										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																								.add(jLabel22))
																						.add(15,
																								15,
																								15)
																						.add(jPanel7Layout
																								.createParallelGroup(
																										org.jdesktop.layout.GroupLayout.LEADING)
																								.add(jTextField10,
																										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																										156,
																										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																								.add(jLabel16)
																								.add(jLabel19)
																								.add(jTextField12,
																										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																										156,
																										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
																.add(org.jdesktop.layout.GroupLayout.LEADING,
																		jTextField13)
																.add(org.jdesktop.layout.GroupLayout.LEADING,
																		jPanel7Layout
																				.createSequentialGroup()
																				.add(jPanel7Layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.TRAILING)
																						.add(org.jdesktop.layout.GroupLayout.LEADING,
																								jLabel17)
																						.add(org.jdesktop.layout.GroupLayout.LEADING,
																								jPanel7Layout
																										.createSequentialGroup()
																										.add(jComboBox4,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(jComboBox5,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.RELATED)
																										.add(jComboBox6,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																						.add(org.jdesktop.layout.GroupLayout.LEADING,
																								jPanel7Layout
																										.createSequentialGroup()
																										.add(jTextField9,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												250,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												org.jdesktop.layout.LayoutStyle.UNRELATED)
																										.add(jTextField3,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																												65,
																												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
																				.add(0,
																						0,
																						Short.MAX_VALUE)))
														.addContainerGap()))));
		jPanel7Layout
				.setVerticalGroup(jPanel7Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel7Layout
								.createSequentialGroup()
								.addContainerGap()
								.add(jPanel7Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel16).add(jLabel8))
								.add(0, 0, 0)
								.add(jPanel7Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jTextField1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jTextField10,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.add(12, 12, 12)
								.add(jPanel7Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel19).add(jLabel18))
								.add(0, 0, 0)
								.add(jPanel7Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jTextField11,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jTextField12,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.UNRELATED)
								.add(jLabel17)
								.add(0, 0, 0)
								.add(jPanel7Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jTextField9,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jTextField3,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.UNRELATED)
								.add(jLabel20)
								.add(0, 0, 0)
								.add(jTextField13,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.UNRELATED)
								.add(jLabel22)
								.add(0, 0, 0)
								.add(jTextField14,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.UNRELATED)
								.add(jLabel21)
								.add(0, 0, 0)
								.add(jPanel7Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jComboBox4,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jComboBox5,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jComboBox6,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		jButton7.setText("Speichern");
		jButton7.setToolTipText("Kunden anlegen");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
				cnw.CreateNewCustomer();
			}
		});

		jButton8.setText("Abbrechen");

		org.jdesktop.layout.GroupLayout jPanel8Layout = new org.jdesktop.layout.GroupLayout(
				jPanel8);
		jPanel8.setLayout(jPanel8Layout);
		jPanel8Layout.setHorizontalGroup(jPanel8Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel8Layout
						.createSequentialGroup()
						.addContainerGap(
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.add(jButton7)
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jButton8)));
		jPanel8Layout.setVerticalGroup(jPanel8Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel8Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.BASELINE)
						.add(jButton7).add(jButton8)));

		org.jdesktop.layout.GroupLayout jDialog1Layout = new org.jdesktop.layout.GroupLayout(
				jDialog1.getContentPane());
		jDialog1.getContentPane().setLayout(jDialog1Layout);
		jDialog1Layout.setHorizontalGroup(jDialog1Layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jDialog1Layout
						.createSequentialGroup()
						.add(jPanel7,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.add(0, 0, Short.MAX_VALUE))
				.add(jPanel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));
		jDialog1Layout.setVerticalGroup(jDialog1Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jDialog1Layout
						.createSequentialGroup()
						.add(jPanel7,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.add(jPanel8,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));

		jPanel9.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Neue DVD anlegen"));

		jLabel9.setText("Barcode");

		jLabel11.setText("Titel");

		jLabel14.setText("Genre");

		jLabel15.setText("FSK");

		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"FSK ab 0 freigegeben", "FSK ab 6 freigegeben",
				"FSK ab 12 freigegeben", "FSK ab 16 freigegeben",
				"FSK ab 18 freigegeben", " " }));

		org.jdesktop.layout.GroupLayout jPanel9Layout = new org.jdesktop.layout.GroupLayout(
				jPanel9);
		jPanel9.setLayout(jPanel9Layout);
		jPanel9Layout
				.setHorizontalGroup(jPanel9Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel9Layout
								.createSequentialGroup()
								.addContainerGap()
								.add(jPanel9Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jPanel9Layout
												.createSequentialGroup()
												.add(jTextField8,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														156,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														org.jdesktop.layout.LayoutStyle.UNRELATED)
												.add(jComboBox3,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														150,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.add(jPanel9Layout
												.createSequentialGroup()
												.add(jTextField4,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														150,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(18, 18, 18)
												.add(jTextField5,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														150,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.add(jPanel9Layout
												.createSequentialGroup()
												.add(jLabel9)
												.add(119, 119, 119)
												.add(jLabel11))
										.add(jPanel9Layout
												.createSequentialGroup()
												.add(jLabel14)
												.add(138, 138, 138)
												.add(jLabel15)))
								.addContainerGap(170, Short.MAX_VALUE)));
		jPanel9Layout
				.setVerticalGroup(jPanel9Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel9Layout
								.createSequentialGroup()
								.add(10, 10, 10)
								.add(jPanel9Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jLabel11).add(jLabel9))
								.add(0, 0, 0)
								.add(jPanel9Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jTextField4,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jTextField5,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.add(12, 12, 12)
								.add(jPanel9Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jLabel15).add(jLabel14))
								.add(0, 0, 0)
								.add(jPanel9Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jTextField8,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jComboBox3,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(360, Short.MAX_VALUE)));

		org.jdesktop.layout.GroupLayout jDialog2Layout = new org.jdesktop.layout.GroupLayout(
				jDialog2.getContentPane());
		jDialog2.getContentPane().setLayout(jDialog2Layout);
		jDialog2Layout.setHorizontalGroup(jDialog2Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jDialog2Layout
						.createSequentialGroup()
						.add(jPanel9,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.add(0, 0, Short.MAX_VALUE)));
		jDialog2Layout.setVerticalGroup(jDialog2Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jPanel9,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("DVD Verwaltung");

		jPanel1.setMinimumSize(new java.awt.Dimension(50, 50));
		jPanel1.setPreferredSize(new java.awt.Dimension(414, 20));

		jSplitPane1.setDividerLocation(150);
		jSplitPane1.setDividerSize(4);

		org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 148,
				Short.MAX_VALUE));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 452,
				Short.MAX_VALUE));

		jSplitPane1.setLeftComponent(jPanel5);

		jSplitPane2.setDividerLocation(150);
		jSplitPane2.setDividerSize(4);
		jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(jTable1);

		org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jScrollPane1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 735,
				Short.MAX_VALUE));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jScrollPane1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 148,
				Short.MAX_VALUE));

		jSplitPane2.setTopComponent(jPanel4);

		org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(jPanel6Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 735,
				Short.MAX_VALUE));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 296,
				Short.MAX_VALUE));

		jSplitPane2.setRightComponent(jPanel6);

		jSplitPane1.setRightComponent(jSplitPane2);

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				org.jdesktop.layout.GroupLayout.TRAILING, jSplitPane1));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jSplitPane1));

		org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 0,
				Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 20,
				Short.MAX_VALUE));

		jPanel3.setAlignmentY(0.0F);

		jButton2.setLabel("+");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel2.setText("Neuer Film ");

		jButton1.setLabel("+");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel1.setText("Neuer Kunde ");

		jLabel4.setText("Suche");

		jLabel3.setText("Filmliste");

		jButton3.setText("i");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setText("i");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jLabel5.setText("Kundenliste");

		jLabel6.setText("Film verleihen");

		jButton5.setText("-");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton6.setText("i");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jLabel7.setText("Filminfo");

		org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel3Layout
								.createSequentialGroup()
								.addContainerGap()
								.add(jPanel3Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.CENTER)
										.add(jButton1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												50,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel1))
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.UNRELATED)
								.add(jPanel3Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.CENTER)
										.add(jButton4,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												50,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel5))
								.add(12, 12, 12)
								.add(jPanel3Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.CENTER)
										.add(jButton2,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												50,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel2))
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.UNRELATED)
								.add(jPanel3Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.CENTER)
										.add(jButton3,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												50,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel3))
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.UNRELATED)
								.add(jPanel3Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.CENTER)
										.add(jButton5,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												50,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel6))
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.UNRELATED)
								.add(jPanel3Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.CENTER)
										.add(jButton6,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												50,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel7))
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.add(jPanel3Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.CENTER)
										.add(jLabel4)
										.add(jTextField2,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												125,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.addContainerGap()));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel3Layout
								.createSequentialGroup()
								.addContainerGap()
								.add(jPanel3Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.TRAILING)
										.add(jPanel3Layout
												.createSequentialGroup()
												.add(jButton4)
												.addPreferredGap(
														org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jLabel5))
										.add(jPanel3Layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING)
												.add(jPanel3Layout
														.createSequentialGroup()
														.add(jButton3)
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jLabel3))
												.add(jPanel3Layout
														.createSequentialGroup()
														.add(jPanel3Layout
																.createParallelGroup(
																		org.jdesktop.layout.GroupLayout.BASELINE)
																.add(jButton2)
																.add(jButton1)
																.add(jTextField2,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jPanel3Layout
																.createParallelGroup(
																		org.jdesktop.layout.GroupLayout.BASELINE)
																.add(jLabel2)
																.add(jLabel1)
																.add(jLabel4)))
												.add(jPanel3Layout
														.createSequentialGroup()
														.add(jButton5)
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jLabel6))
												.add(jPanel3Layout
														.createSequentialGroup()
														.add(jButton6)
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jLabel7))))
								.addContainerGap(16, Short.MAX_VALUE)));

		jMenu1.setText("Datei");

		jMenuItem1.setText("Datenbank");
		jMenu1.add(jMenuItem1);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("Edit");
		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						895, Short.MAX_VALUE)
				.add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));
		layout.setVerticalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.add(jPanel3,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.add(1, 1, 1)
						.add(jPanel1,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								456, Short.MAX_VALUE)
						.add(1, 1, 1)
						.add(jPanel2,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)));

		pack();
	}// </editor-fold>

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		NewCustomer nc = new NewCustomer();
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:

	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JComboBox jComboBox3;
	private javax.swing.JComboBox jComboBox4;
	private javax.swing.JComboBox jComboBox5;
	private javax.swing.JComboBox jComboBox6;
	private javax.swing.JDialog jDialog1;
	private javax.swing.JDialog jDialog2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSplitPane jSplitPane1;
	private javax.swing.JSplitPane jSplitPane2;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField10;
	private javax.swing.JTextField jTextField11;
	private javax.swing.JTextField jTextField12;
	private javax.swing.JTextField jTextField13;
	private javax.swing.JTextField jTextField14;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField8;
	private javax.swing.JTextField jTextField9;
	// End of variables declaration
}
